# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Juanes\sipaBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: 123456, roles: ROLE_ADMIN }
        user_db:
            entity: { class: JuanessipaBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin/user
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/user, roles: ROLE_ADMIN }
        - { path: /admin/actividades, roles: ROLE_ADMIN }
        - { path: /admin/registrovisitas, roles: ROLE_ADMIN }
        - { path: /admin/productos, roles: ROLE_ADMIN }
        - { path: /admin/prodflias, roles: ROLE_ADMIN }
        - { path: /admin/familias, roles: ROLE_ADMIN }
        - { path: /admin/municipios, roles: ROLE_ADMIN }
        - { path: /admin/responsables, roles: ROLE_ADMIN }
        - { path: /admin/personas, roles: ROLE_ADMIN }
        - { path: /detallevisitas, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }