# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  sipaBundle.service.listener:
    class: Juanes\sipaBundle\Listener\LoadDataListener
    # arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }