Juanes\sipaBundle\Entity\Detallevisitas:
    type: entity
    table: detallevisitas
    
    id:
        idregactdet:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRegActDet
            generator:
                strategy: IDENTITY
    fields:
        cantidad:
            type: integer
            nullable: false
            options:
                unsigned: false
        estadovis:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: estadoVis
        observa:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: observa
    manyToOne:
        jumdetreg:
            targetEntity: Registrovisitas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumregvis
            joinColumn:
                name: detregvis_id
                referencedColumnName: idRegVis
            orphanRemoval: false
        jumdetact:
            targetEntity: Actividades
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumacti
            joinColumn:
                name: detact_id
                referencedColumnName: idActividad
            orphanRemoval: false
        jumdetpro:
            targetEntity: Productos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumpro
            joinColumn:
                name: detpro_id
                referencedColumnName: idProducto
            orphanRemoval: false
    lifecycleCallbacks: {  }
