Juanes\sipaBundle\Entity\Familias:
    type: entity
    table: familias
    indexes:
        idFlia:
            columns:
                - idFlia    
    id:
        idflia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idFlia
            generator:
                strategy: IDENTITY
    fields:
        nomflia:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nomFlia
        vereda:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: verda
        finca:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: finca
    manyToOne:
        jumflimun:
            targetEntity: Municipios
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jummunfli
            joinColumn:
                name: idMunicipio
                referencedColumnName: idMunicipio
            orphanRemoval: false

    oneToMany:
        jumflirep:
            targetEntity: Responsables
            mappedBy: jumresfli

        jumflireg:
            targetEntity: Registrovisitas
            mappedBy: jumregfli

        jumflipf:
            targetEntity: Prodflias
            mappedBy: jumpffli

        jumfliper:
            targetEntity: Personas
            mappedBy: jumperfli

    lifecycleCallbacks: {  }