Juanes\sipaBundle\Entity\Municipios:
    type: entity
    table: municipios
    indexes:
        idMunicipio:
            columns:
                - idMunicipio
    id:
        idmunicipio:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idMunicipio
            generator:
                strategy: IDENTITY
    fields:
        nommunicipio:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nomMunicipio
    oneToMany:
        jummunfli:
            targetEntity: Familias
            mappedBy: jumflimun
    lifecycleCallbacks: {  }