Juanes\sipaBundle\Entity\Personas:
    type: entity
    table: personas
    uniqueConstraints:
        idPersona:
            columns:
                - idPersona
    id:
        idpersona:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idPersona
            generator:
                strategy: IDENTITY
    fields:
        docpers:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: docPers
        nompers:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nomPers
        apepers:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: apePers

    manyToOne:
        jumperfli:
            targetEntity: Familias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumfliper
            joinColumn:
                name: idFlia
                referencedColumnName: idFlia
            orphanRemoval: false
    oneToMany:
        jumperrep:
            targetEntity: Responsables
            mappedBy: jumresper
            
    lifecycleCallbacks: {  }