Juanes\sipaBundle\Entity\Prodflias:
    type: entity
    table: prodflias
    indexes:
        idProducto:
            columns:
                - idProducto
        idFamilia:
            columns:
                - idFlia
    id:
        idProdFlia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProdFlia
            generator:
                strategy: IDENTITY
    manyToOne:
        idProducto:
            targetEntity: Productos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idProducto:
                    referencedColumnName: idProducto
            orphanRemoval: false
        idFlia:
            targetEntity: Familias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idFlia:
                    referencedColumnName: idFlia
            orphanRemoval: false
    lifecycleCallbacks: {  }
