Juanes\sipaBundle\Entity\Prodflias:
    type: entity
    table: prodflias
    indexes:
        idProdFlia:
            columns:
                - idProdFlia
    id:
        idprodflia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProdFlia
            generator:
                strategy: IDENTITY
    manyToOne:
        jumpfpro:
            targetEntity: Productos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumpropf
            joinColumn:
                name: idProducto
                referencedColumnName: idProducto
            orphanRemoval: false
        jumpffli:
            targetEntity: Familias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumflipf
            joinColumn:
                name: idFlia
                referencedColumnName: idFlia
            orphanRemoval: false
    lifecycleCallbacks: {  }
