Juanes\sipaBundle\Entity\Productos:
    type: entity
    table: productos
    indexes:
        idProducto:
            columns:
                - idProducto
    id:
        idproducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProducto
            generator:
                strategy: IDENTITY
    fields:
        nomproducto:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nomProducto
    oneToMany:
        jumpro:
            targetEntity: Detallevisitas
            mappedBy: jumdetpro
            
        jumpropf:
            targetEntity: Prodflias
            mappedBy: jumpfpro
    lifecycleCallbacks: {  }