Juanes\sipaBundle\Entity\Registrovisitas:
    type: entity
    table: registrovisitas
    indexes:
        idRegVis:
            columns:
                - idRegVis
    id:
        idregvis:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRegVis
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: false
        archivo:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    manyToOne:
        jumreguse:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumuser
            joinColumn:
                name: idUser
                referencedColumnName: idUser
            orphanRemoval: false
        jumregfli:
            targetEntity: Familias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumflireg
            joinColumn:
                name: idFlia
                referencedColumnName: idFlia
            orphanRemoval: false
 
    oneToMany:
        jumregvis:
            targetEntity: Detallevisitas
            mappedBy: jumdetreg
    lifecycleCallbacks: {  }