Juanes\sipaBundle\Entity\Responsables:
    type: entity
    table: responsables
    uniqueConstraints:
        idRes:
            columns:
                - idRes
    id:
        idres:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idRes
            generator:
                strategy: IDENTITY
    fields:
        estadores:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: estadoRes
        fechares:
            type: date
            nullable: false
            column: fechaRes
    manyToOne:
        jumresfli:
            targetEntity: Familias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumflirep
            joinColumn:
                name: idFlia
                referencedColumnName: idFlia
            orphanRemoval: false
        jumresper:
            targetEntity: Personas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: jumperrep
            joinColumn:
                name: idPersona
                referencedColumnName: idPersona
            orphanRemoval: false
    lifecycleCallbacks: {  }