Juanes\sipaBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        idUser:
            columns:
                - idUser
    id:
        iduser:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idUser
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: username
        nomuser:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: nomUser
        apeuser:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: apeUser
        docuser:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: docUser
        password:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
            column: password
    oneToMany:
        jumuser:
            targetEntity: Registrovisitas
            mappedBy: jumreguse
    lifecycleCallbacks: {  }
