admin_personas_index:
    path:     /
    defaults: { _controller: "JuanessipaBundle:Personas:index" }
    methods:  GET

admin_personas_show:
    path:     /{id}/show
    defaults: { _controller: "JuanessipaBundle:Personas:show" }
    methods:  GET

admin_personas_new:
    path:     /new
    defaults: { _controller: "JuanessipaBundle:Personas:new" }
    methods:  [GET, POST]

admin_personas_edit:
    path:     /{id}/edit
    defaults: { _controller: "JuanessipaBundle:Personas:edit" }
    methods:  [GET, POST]

admin_personas_delete:
    path:     /{id}/delete
    defaults: { _controller: "JuanessipaBundle:Personas:delete" }
    methods:  DELETE
