admin_productos_index:
    path:     /
    defaults: { _controller: "JuanessipaBundle:Productos:index" }
    methods:  GET

admin_productos_show:
    path:     /{id}/show
    defaults: { _controller: "JuanessipaBundle:Productos:show" }
    methods:  GET

admin_productos_new:
    path:     /new
    defaults: { _controller: "JuanessipaBundle:Productos:new" }
    methods:  [GET, POST]

admin_productos_edit:
    path:     /{id}/edit
    defaults: { _controller: "JuanessipaBundle:Productos:edit" }
    methods:  [GET, POST]

admin_productos_delete:
    path:     /{id}/delete
    defaults: { _controller: "JuanessipaBundle:Productos:delete" }
    methods:  DELETE
